MONGODB_HOST: mongodb-{{ env }}.inkweave.dpdns.org   #mongodb-dev.inkweave.dpdns.org
REDIS_HOST: redis-{{ env }}.inkweave.dpdns.org
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.inkweave.dpdns.org
CART_HOST: cart.backend-alb-{{ env }}.inkweave.dpdns.org
USER_HOST: user.backend-alb-{{ env }}.inkweave.dpdns.org
RABBITMQ_HOST: rabbitmq.{{ env }}.inkweave.dpdns.org
MYSQL_HOST: mysql-{{ env }}.inkweave.dpdns.org
SHIPPING_HOST: shipping.backend-alb-{{ env }}.inkweave.dpdns.org
PAYMENT_HOST: payment.backend-alb-{{ env }}.inkweave.dpdns.org